"""Packaged documentation and cross-agent skill installation."""

import argparse
import importlib.metadata
import os
import re
import sys
import tempfile
from collections.abc import Sequence
from importlib.resources import files
from pathlib import Path
from typing import NamedTuple

PACKAGE_NAME = "deep-transcribe"
SKILL_DIRNAME = "deep-transcribe"
SKILL_FORMAT = "f02"
DISCOVERY_VERSION = "0.1.11"
YTDLP_DISCOVERY_CUTOFF = "2026-08-20T00:00:00Z"

SURFACE_PORTABLE = "portable"
SURFACE_CLAUDE = "claude"
SURFACE_AGENTS_MD = "agents-md"
ALL_SURFACES = frozenset({SURFACE_PORTABLE, SURFACE_CLAUDE, SURFACE_AGENTS_MD})

PORTABLE_SKILL_REL = Path(".agents/skills") / SKILL_DIRNAME
CLAUDE_SKILL_REL = Path(".claude/skills") / SKILL_DIRNAME

AGENTS_BEGIN_PREFIX = "<!-- BEGIN DEEP TRANSCRIBE INTEGRATION"
AGENTS_END_MARKER = "<!-- END DEEP TRANSCRIBE INTEGRATION -->"

_VERSION_PLACEHOLDER = "__DEEP_TRANSCRIBE_VERSION__"
_YTDLP_CUTOFF_PLACEHOLDER = "__YTDLP_CUTOFF__"
_PYPI_RELEASE_RE = re.compile(r"^\d+(?:\.\d+)*(?:\.post\d+)?$")
_FORMAT_RE = re.compile(r"format=f(\d+)")
_AGENTS_BLOCK_RE = re.compile(
    re.escape(AGENTS_BEGIN_PREFIX) + r".*?" + re.escape(AGENTS_END_MARKER),
    re.DOTALL,
)
_AGENTS_FORMAT_RE = re.compile(re.escape(AGENTS_BEGIN_PREFIX) + r"\s+format=f(\d+)")


class InstallResult(NamedTuple):
    """The outcome for one requested installation surface."""

    surface: str
    path: Path
    action: str


def _resource_text(*parts: str) -> str:
    resource = files("deep_transcribe")
    for part in parts:
        resource = resource.joinpath(part)
    return resource.read_text(encoding="utf-8")


def get_docs_content() -> str:
    """Return the complete operational guide packaged with this release."""
    return _resource_text("resources", "docs.md")


def get_skill_template() -> str:
    """Return the authored skill before release-version substitution."""
    return _resource_text("resources", "skill", "SKILL.md")


def get_openai_metadata() -> str:
    """Return the authored OpenAI skill metadata."""
    return _resource_text("resources", "skill", "agents", "openai.yaml")


def is_pypi_release(version_string: str) -> bool:
    """Return whether a version can be used as an exact published PyPI pin."""
    return bool(_PYPI_RELEASE_RE.fullmatch(version_string))


def deep_transcribe_version() -> str:
    """Return an exact runnable pin for the installed or discovery release."""
    try:
        installed = importlib.metadata.version(PACKAGE_NAME)
    except importlib.metadata.PackageNotFoundError:
        return DISCOVERY_VERSION
    return installed if is_pypi_release(installed) else DISCOVERY_VERSION


def compose_skill(version: str | None = None) -> str:
    """Render the authored skill with an exact Deep Transcribe release pin."""
    pin = deep_transcribe_version() if version is None else version
    if not is_pypi_release(pin):
        raise ValueError(f"skill runner version must be an exact release: {pin!r}")
    return (
        get_skill_template()
        .replace(_VERSION_PLACEHOLDER, pin)
        .replace(_YTDLP_CUTOFF_PLACEHOLDER, YTDLP_DISCOVERY_CUTOFF)
    )


def _generated_html_marker(surface: str) -> str:
    return (
        "<!-- DO NOT EDIT: generated by `deep-transcribe --install-skill` "
        f"(format={SKILL_FORMAT} surface={surface}) -->"
    )


def _generated_yaml_marker(surface: str) -> str:
    return (
        "# DO NOT EDIT: generated by `deep-transcribe --install-skill` "
        f"(format={SKILL_FORMAT} surface={surface})"
    )


def _insert_after_frontmatter(content: str, marker: str) -> str:
    delimiter = "\n---\n"
    if content.startswith("---\n") and (end := content.find(delimiter, 4)) != -1:
        head = content[: end + len(delimiter)]
        body = content[end + len(delimiter) :]
        return f"{head}\n{marker}\n\n{body}"
    return f"{marker}\n\n{content}"


def render_skill_bundle(version: str | None = None) -> dict[Path, str]:
    """Render every file in a complete installable skill bundle."""
    return {
        Path("SKILL.md"): _insert_after_frontmatter(
            compose_skill(version),
            _generated_html_marker("skill-md"),
        ),
        Path("agents/openai.yaml"): (
            f"{_generated_yaml_marker('openai-yaml')}\n{get_openai_metadata()}"
        ),
    }


def discovery_skill_bundle() -> dict[Path, str]:
    """Return the deterministic bundle committed for public skill discovery."""
    return render_skill_bundle(DISCOVERY_VERSION)


def _format_number() -> int:
    return int(SKILL_FORMAT.removeprefix("f"))


def _existing_format(path: Path) -> int | None:
    if not path.is_file():
        return None
    match = _FORMAT_RE.search(path.read_text(encoding="utf-8"))
    return int(match.group(1)) if match else 0


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            output.write(content)
        os.replace(temp_path, path)
    except BaseException:
        temp_path.unlink(missing_ok=True)
        raise


def _write_bundle(skill_dir: Path, surface: str, bundle: dict[Path, str]) -> InstallResult:
    targets = {relative: skill_dir / relative for relative in bundle}
    for target in targets.values():
        existing_format = _existing_format(target)
        if existing_format is not None and existing_format > _format_number():
            return InstallResult(surface, target, "blocked-newer")

    if all(
        target.is_file() and target.read_text(encoding="utf-8") == bundle[relative]
        for relative, target in targets.items()
    ):
        return InstallResult(surface, skill_dir / "SKILL.md", "unchanged")

    action = "updated" if any(target.exists() for target in targets.values()) else "installed"

    staged: list[tuple[Path, Path]] = []
    try:
        for relative, target in targets.items():
            target.parent.mkdir(parents=True, exist_ok=True)
            descriptor, temp_name = tempfile.mkstemp(
                prefix=f".{target.name}.",
                dir=target.parent,
            )
            temp_path = Path(temp_name)
            with os.fdopen(descriptor, "w", encoding="utf-8") as output:
                output.write(bundle[relative])
            staged.append((temp_path, target))

        # Publish supporting metadata first and SKILL.md last. A visible skill therefore
        # never points at bundle content that failed to materialize.
        for temp_path, target in sorted(staged, key=lambda pair: pair[1].name == "SKILL.md"):
            os.replace(temp_path, target)
    finally:
        for temp_path, _target in staged:
            temp_path.unlink(missing_ok=True)

    return InstallResult(surface, skill_dir / "SKILL.md", action)


def agents_md_block(version: str | None = None) -> str:
    """Render the compact, marker-bounded project instruction block."""
    pin = deep_transcribe_version() if version is None else version
    if not is_pypi_release(pin):
        raise ValueError(f"skill runner version must be an exact release: {pin!r}")
    return (
        f"{AGENTS_BEGIN_PREFIX} format={SKILL_FORMAT} surface=agents-md -->\n"
        "## Deep Transcribe\n\n"
        "Use Deep Transcribe for audio and video transcription and cache-aware refinement.\n\n"
        "- In a Deep Transcribe source checkout, run `uv run deep-transcribe --docs`.\n"
        "- Otherwise, use the installed command only if `deep-transcribe --docs` succeeds.\n"
        "- If the command is missing or rejects `--docs`, use the exact pinned runner below.\n"
        "- Use the same verified runner with `--skill` for the complete agent workflow.\n"
        "- Preserve the same source and workspace when refining a reviewed result.\n"
        "- Exact pinned runner: `uvx --exclude-newer-package "
        f"yt-dlp={YTDLP_DISCOVERY_CUTOFF} --from deep-transcribe=={pin} deep-transcribe`.\n\n"
        f"{AGENTS_END_MARKER}"
    )


def _replace_all_agents_blocks(existing: str, block: str) -> str:
    matches = list(_AGENTS_BLOCK_RE.finditer(existing))
    if not matches:
        return existing
    head = existing[: matches[0].start()]
    middle = "".join(
        existing[matches[index - 1].end() : matches[index].start()]
        for index in range(1, len(matches))
    )
    tail = existing[matches[-1].end() :]
    return head + block + middle + tail


def update_agents_md(path: Path, version: str | None = None) -> InstallResult:
    """Insert or refresh only the generated Deep Transcribe block in AGENTS.md."""
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    if existing is not None and (match := _AGENTS_FORMAT_RE.search(existing)):
        if int(match.group(1)) > _format_number():
            return InstallResult(SURFACE_AGENTS_MD, path, "blocked-newer")

    block = agents_md_block(version)
    if existing is None or AGENTS_BEGIN_PREFIX not in existing:
        if not existing:
            new_content = block + "\n"
        else:
            separator = "\n" if existing.endswith("\n") else "\n\n"
            new_content = existing + separator + block + "\n"
    else:
        new_content = _replace_all_agents_blocks(existing, block)

    if existing == new_content:
        return InstallResult(SURFACE_AGENTS_MD, path, "unchanged")
    action = "updated" if existing is not None else "installed"
    _atomic_write(path, new_content)
    return InstallResult(SURFACE_AGENTS_MD, path, action)


def _inside_git_repository(path: Path) -> bool:
    return any((candidate / ".git").exists() for candidate in (path, *path.parents))


def _print_install_results(results: list[InstallResult], project_root: Path | None) -> None:
    print("Deep Transcribe skill installation:")
    for result in results:
        print(f"  {result.action:>13}  {result.surface:<10}  {result.path}")
    if project_root is not None and not _inside_git_repository(project_root):
        print(
            f"\nNote: {project_root} is not inside a git repository. "
            "Run this command from the intended project root, or use --agent-base for "
            "a deliberate global or custom install."
        )


def install_skill(
    agent_base: str | Path | None = None,
    *,
    project_root: str | Path | None = None,
    surfaces: frozenset[str] | None = None,
) -> list[InstallResult]:
    """Install the complete skill bundle and return one result per selected surface."""
    if agent_base is not None and surfaces is not None:
        raise ValueError("surfaces cannot be combined with an explicit agent base")

    bundle = render_skill_bundle()
    if agent_base is not None:
        skill_dir = Path(agent_base).expanduser().resolve() / "skills" / SKILL_DIRNAME
        results = [_write_bundle(skill_dir, "agent-base", bundle)]
        _print_install_results(results, None)
        return results

    selected = ALL_SURFACES if surfaces is None else surfaces
    unknown = selected - ALL_SURFACES
    if unknown:
        raise ValueError(f"unknown skill surfaces: {', '.join(sorted(unknown))}")

    root = Path.cwd() if project_root is None else Path(project_root)
    root = root.expanduser().resolve()
    results: list[InstallResult] = []
    if SURFACE_PORTABLE in selected:
        results.append(_write_bundle(root / PORTABLE_SKILL_REL, SURFACE_PORTABLE, bundle))
    if SURFACE_CLAUDE in selected:
        results.append(_write_bundle(root / CLAUDE_SKILL_REL, SURFACE_CLAUDE, bundle))
    if SURFACE_AGENTS_MD in selected:
        results.append(update_agents_md(root / "AGENTS.md"))
    _print_install_results(results, root)
    return results


def sync_repository_skill(repository_root: str | Path) -> list[InstallResult]:
    """Regenerate checked-in discovery and repository-local skill bundles."""
    root = Path(repository_root).expanduser().resolve()
    bundle = discovery_skill_bundle()
    destinations = (
        ("discovery", root / "skills" / SKILL_DIRNAME),
        (SURFACE_PORTABLE, root / PORTABLE_SKILL_REL),
        (SURFACE_CLAUDE, root / CLAUDE_SKILL_REL),
    )
    return [_write_bundle(destination, surface, bundle) for surface, destination in destinations]


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate repository skill copies for maintainers."""
    parser = argparse.ArgumentParser(description="Regenerate Deep Transcribe skill copies")
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root containing skills/, .agents/, and .claude/",
    )
    args = parser.parse_args(argv)
    results = sync_repository_skill(args.repository_root)
    _print_install_results(results, None)
    return 1 if any(result.action == "blocked-newer" for result in results) else 0


if __name__ == "__main__":
    sys.exit(main())
